# Generated by Django 4.0.3 on 2022-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'fiction'), ('religious', 'religious'), ('computer science', 'computer science'), ('engineering', 'engineering'), ('pyscological', 'pyscological')], max_length=5000, null=True),
        ),
    ]
