# Generated by Django 5.1.2 on 2024-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'fiction'), ('religious', 'religious'), ('Programming/Web Development', 'Programming/Web Development'), ('Self-Help', 'Self-Help')], max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='pending', max_length=200, null=True),
        ),
    ]
